export const MOCK_PROJECTS = [
  {
    id: 101,
    name: "Sai Shankar by Sai Life",
    slug: "sai-shankar-sai-life",
    location: "M.G. Road, Pant Nagar, Ghatkopar East, Mumbai",
    city: "Mumbai",
    builder: "Sai Life Realtors",
    price_display: "₹ 1.65 Cr Onwards",
    status: "under-construction",
    cover_image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    bhk_options: "2, 3 BHK & Jodi Options (4, 5 BHK)",
    possession: "Dec 2028",
    rera_number: "P51800054397",
    category: "Residential",
    tagline: "3 Magnificent Wings of Modern Luxury in Pant Nagar",
    gallery: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=80"
    ],
    highlights: [
      "3 Grand Wings Spanning a 0.77-Acre Land Parcel",
      "Spacious 2 & 3 BHK Layouts with Large Jodi Combinations",
      "Private Mini-Theatre & Air-Conditioned Gymnasium",
      "Double-Height Designer Reception Lobby",
      "Podium-Level Multi-Level Car Parking Bay",
      "Prime Strategic Location on M.G. Road, Pant Nagar"
    ],
    amenities: ["Gymnasium", "Mini Theatre", "Multipurpose Hall", "Indoor Games Room", "Podium Parking", "Landscaped Gardens", "24/7 Security", "EV Charging"],
    description: "Sai Shankar by Sai Life is a landmark residential development rising across 0.77 acres on M.G. Road in Pant Nagar, Ghatkopar East. Designed across three magnificent wings, it offers meticulously crafted 2 BHK and 3 BHK luxury residences along with expansive Jodi combinations. Featuring a private mini-theatre, state-of-the-art gymnasium, indoor recreational zone, and seamless connectivity to Eastern Express Highway, Metro, and railway transit.",
    is_published: true,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 102,
    name: "PSK Aura",
    slug: "psk-aura-ghatkopar",
    location: "Hingwala Lane, Saibaba Nagar, Pant Nagar, Ghatkopar East, Mumbai",
    city: "Mumbai",
    builder: "PSK Group",
    price_display: "₹ 1.75 Cr Onwards",
    status: "under-construction",
    cover_image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80",
    bhk_options: "2, 3 & 4 BHK",
    possession: "March 2029",
    rera_number: "P51800080013",
    category: "Residential",
    tagline: "Boutique G+20 High-Rise Living in Prime Ghatkopar",
    gallery: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=1200&q=80",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&q=80"
    ],
    highlights: [
      "G+20 Storey Standalone Boutique High-Rise Tower",
      "Open-to-Sky Landscaped Podium Garden",
      "3 Levels of Secure Basement Parking with EV Stations",
      "Exclusive Mini-Theatre, Reading Library & Toddler Zone",
      "450m from Proposed Pantnagar Metro & 600m from Ghatkopar Station",
      "Vastu-Compliant Architectural Floor Plans"
    ],
    amenities: ["Fitness Centre", "Open Podium Garden", "Mini Theatre", "Multipurpose Court", "Reading Library", "Kids Play Zone", "Basement Parking", "EV Charging"],
    description: "PSK Aura is an exclusive G+20 storey boutique residential tower located on Hingwala Lane, Pant Nagar, Ghatkopar East. Offering ultra-luxurious 2, 3, and 4 BHK residences, PSK Aura seamlessly blends contemporary architectural aesthetics with serene lifestyle amenities including an open-to-sky podium garden, fitness centre, reading lounge, and 3 basement parking tiers, all within walking distance from Ghatkopar station and metro.",
    is_published: true,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 103,
    name: "Silver Stellar",
    slug: "silver-stellar-ghatkopar",
    location: "Bhanushali Lane, Pant Nagar, Ghatkopar East, Mumbai",
    city: "Mumbai",
    builder: "Silver Group",
    price_display: "₹ 2.45 Cr Onwards",
    status: "under-construction",
    cover_image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1200&q=80",
    bhk_options: "3 & 4 BHK",
    possession: "Dec 2028",
    rera_number: "P51800056223",
    category: "Residential",
    tagline: "Ultra-Spacious 3 & 4 BHK Residences by Silver Group",
    gallery: [
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80",
      "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1200&q=80",
      "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=1200&q=80"
    ],
    highlights: [
      "Ultra-Spacious Luxury 3 & 4 BHK Residences",
      "Rooftop Sky Deck & Horizon Stargazing Lounge",
      "Grand Double-Height Italian Marble Entrance Lobby",
      "High-Speed Elevators with Power Backup",
      "Located in Prestigious Bhanushali Lane, Pant Nagar",
      "Smart Home Automation & Multi-Tier Biometric Security"
    ],
    amenities: ["Sky Lounge", "Infinity View Deck", "Gymnasium", "Italian Marble Lobby", "Yoga Pavilion", "Automated Parking", "24/7 Security"],
    description: "Silver Stellar by Silver Group represents the pinnacle of spacious family living in Ghatkopar East. Situated in the serene neighborhood of Bhanushali Lane, Pant Nagar, this iconic standalone luxury tower offers palatial 3 & 4 BHK homes featuring floor-to-ceiling glass windows, imported marble finishes, a rooftop sky deck, and bespoke lifestyle amenities tailored for Mumbai's discerning elite.",
    is_published: true,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 104,
    name: "Silver House",
    slug: "silver-house-ghatkopar",
    location: "Tilak Road, Opp. Gurukrupa Hotel, Ghatkopar East, Mumbai",
    city: "Mumbai",
    builder: "Silver Group",
    price_display: "₹ 1.15 Cr Onwards",
    status: "under-construction",
    cover_image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    bhk_options: "Boutique Offices & High-Street Retail",
    possession: "Dec 2029",
    rera_number: "PC1180002500363",
    category: "Commercial",
    tagline: "G+16 Storey Iconic Commercial Landmark on Tilak Road",
    gallery: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80",
      "https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=1200&q=80",
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
      "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200&q=80"
    ],
    highlights: [
      "Iconic G+16 Storey Glass Facade Commercial Landmark",
      "Double-Height Grand Drop-Off Reception Lobby",
      "Rooftop Business Lounge, Cafeteria & Open-Air Screening",
      "Pickle / Paddle Ball Court & Open-to-Sky Podium Deck",
      "2 Levels of Basement & Multi-Level Podium Parking",
      "Located on High-Footfall Tilak Road, Ghatkopar East"
    ],
    amenities: ["Business Lounge", "High-Speed Elevators", "Paddle Ball Court", "Cafeteria", "Amphitheatre", "Conference Rooms", "Basement Parking", "24/7 Security"],
    description: "Silver House is a premier G+16 storey next-generation commercial tower developed by Silver Group on Tilak Road, Ghatkopar East. Built to world-class Grade-A corporate standards, it features flexible boutique office suites, high-visibility retail spaces, double-height grand entrance reception, rooftop open-air amphitheatre, paddle ball court, and advanced building management systems.",
    is_published: true,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 105,
    name: "One Alag",
    slug: "alag-one-chembur",
    location: "Central Chembur / Ghatkopar Link, Chembur, Mumbai",
    city: "Mumbai",
    builder: "Alag Group",
    price_display: "₹ 95 Lac Onwards",
    status: "under-construction",
    cover_image: "https://images.unsplash.com/photo-1554469384-e58fac16e23a?w=1200&q=80",
    bhk_options: "Smart Commercial Suites & Retail Outlets",
    possession: "Dec 2028",
    rera_number: "P51800052341",
    category: "Commercial",
    tagline: "Next-Gen Commercial & Retail Hub by Alag Group",
    gallery: [
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1200&q=80",
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
      "https://images.unsplash.com/photo-1497215842964-222b430dc094?w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80"
    ],
    highlights: [
      "Grade-A Commercial Infrastructure by Reputed Alag Group",
      "High-Visibility Frontage on High Traffic Corridor",
      "Flexible Office Layouts with Self-Contained Restrooms",
      "Double-Height Designer Lobby with Biometric Access",
      "Minutes to Eastern Freeway, BKC Connector & LTT Station",
      "High Rental Yield & Capital Appreciation Potential"
    ],
    amenities: ["Grade-A Lobby", "High-Speed Elevators", "Business Center", "Power Backup", "BMS Surveillance", "Visitor Parking", "EV Charging"],
    description: "One Alag by Alag Group is a high-profile commercial and retail hub situated along the prime Chembur-Ghatkopar growth corridor. Offering contemporary commercial suites and prime ground-level retail spaces, One Alag provides businesses with superior connectivity, modern architectural design, and state-of-the-art corporate infrastructure.",
    is_published: true,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 106,
    name: "Shubham Artesia",
    slug: "shubham-artesia-ghatkopar",
    location: "328, Ramanarayan Narkar Marg, Pant Nagar, Ghatkopar East, Mumbai",
    city: "Mumbai",
    builder: "Shubham Group",
    price_display: "₹ 1.80 Cr Onwards",
    status: "under-construction",
    cover_image: "https://images.unsplash.com/photo-1613490900233-141c5560d75d?w=1200&q=80",
    bhk_options: "2 & 3 BHK",
    possession: "Dec 2027",
    rera_number: "P51800079435",
    category: "Residential",
    tagline: "20-Storey Architectural Wonder in Heart of Pant Nagar",
    gallery: [
      "https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=1200&q=80",
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=1200&q=80",
      "https://images.unsplash.com/photo-1616137466211-f939a420be84?w=1200&q=80",
      "https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?w=1200&q=80"
    ],
    highlights: [
      "Magnificent 20-Storey Architectural High-Rise",
      "Air-Conditioned Gymnasium & Wellness Studio",
      "Grand Banquet Hall with Landscaped Party Lawn",
      "High-Street Retail Boulevard at Ground Level",
      "2 Minutes from Ghatkopar Railway Station & Metro",
      "Double-Height Grand Entrance Lobby with Concierge"
    ],
    amenities: ["AC Gymnasium", "Banquet Hall", "Party Lawn", "High-Street Retail", "Kids Play Area", "Smart Security", "Podium Parking"],
    description: "Shubham Artesia by Shubham Group is a 20-storey architectural masterpiece located on Ramanarayan Narkar Marg in Pant Nagar, Ghatkopar East. Offering lavish 2 and 3 BHK luxury residences, the project features ground-level high-street retail, an air-conditioned fitness club, a grand banquet hall with party lawn, and unmatched transit connectivity to Eastern Express Highway and metro station.",
    is_published: true,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 107,
    name: "MICL Aaradhya OnePark",
    slug: "micl-aaradhya-onepark",
    location: "60ft Road, Ghatkopar East, Mumbai",
    city: "Mumbai",
    builder: "MICL Group",
    price_display: "₹ 2.80 Cr Onwards",
    status: "new-launch",
    cover_image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    bhk_options: "3, 4 & 5 BHK",
    possession: "Dec 2026",
    rera_number: "P51800000001",
    category: "Residential",
    tagline: "Ultra Luxury High-Rise on 60ft Road",
    gallery: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=80"
    ],
    highlights: ["Rooftop Infinity Sky Pool", "Double-Height Grand Entrance Lobby", "Zen Garden & Yoga Pavilion", "Automated Smart Tower Parking"],
    amenities: ["Infinity Pool", "Gymnasium", "Concierge", "Sky Lounge", "24/7 Security"],
    description: "Aaradhya OnePark brings ultra-luxury living to the prestigious 60ft Road in Ghatkopar East. A perfect blend of contemporary glass architecture, gold accents, and timeless elegance with panoramic city vistas.",
    is_published: true,
    is_featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 108,
    name: "Adani The Views",
    slug: "adani-the-views",
    location: "Pant Nagar, Ghatkopar East, Mumbai",
    city: "Mumbai",
    builder: "Adani Realty",
    price_display: "₹ 1.99 Cr Onwards",
    status: "under-construction",
    cover_image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80",
    bhk_options: "2, 3 & 4 BHK",
    possession: "Dec 2027",
    rera_number: "P51900031165",
    category: "Residential",
    tagline: "Signature 200-ft Skywalk & Podium Living",
    gallery: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=1200&q=80",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&q=80"
    ],
    highlights: ["200-foot Signature Skywalk", "Landscaped Podium Garden", "Adani Realty Build Quality Assurance", "10 Mins to Eastern Express Highway"],
    amenities: ["Skywalk", "Clubhouse", "Gymnasium", "Swimming Pool", "Kids Play Area"],
    description: "Adani The Views in Pant Nagar, Ghatkopar East offers premium 2, 3 & 4 BHK residences featuring a signature 200-foot elevated skywalk, expansive podium gardens, and top-tier luxury amenities.",
    is_published: true,
    is_featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];
