const mysql = require('mysql2/promise');

const allProjects = [
  // --- 1. CORE 6 FEATURED GHATKOPAR REAL PROJECTS (OFFICIAL ASSETS) ---
  {
    name: "Sai Shankar by Sai Life",
    slug: "sai-shankar-sai-life",
    location: "M.G. Road, Pant Nagar, Ghatkopar East, Mumbai",
    city: "Mumbai",
    builder: "Sai Life Realtors",
    price_display: "₹ 1.65 Cr Onwards",
    price_numeric: 16500000,
    status: "under-construction",
    cover_image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    bhk_options: "2, 3 BHK & Jodi Options (4, 5 BHK)",
    min_bhk: 2,
    max_bhk: 5,
    possession: "Dec 2028",
    rera_number: "P51800054397",
    category: "Residential",
    tagline: "3 Magnificent Wings of Modern Luxury in Pant Nagar",
    gallery: JSON.stringify([
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=80"
    ]),
    highlights: JSON.stringify([
      "3 Grand Wings Spanning a 0.77-Acre Land Parcel",
      "Spacious 2 & 3 BHK Layouts with Large Jodi Combinations",
      "Private Mini-Theatre & Air-Conditioned Gymnasium",
      "Double-Height Designer Reception Lobby",
      "Podium-Level Multi-Level Car Parking Bay",
      "Prime Strategic Location on M.G. Road, Pant Nagar"
    ]),
    amenities: JSON.stringify(["Gymnasium", "Mini Theatre", "Multipurpose Hall", "Indoor Games Room", "Podium Parking", "Landscaped Gardens", "24/7 Security", "EV Charging"]),
    description: "Sai Shankar by Sai Life is a landmark residential development rising across 0.77 acres on M.G. Road in Pant Nagar, Ghatkopar East. Designed across three magnificent wings, it offers meticulously crafted 2 BHK and 3 BHK luxury residences along with expansive Jodi combinations. Featuring a private mini-theatre, state-of-the-art gymnasium, indoor recreational zone, and seamless connectivity to Eastern Express Highway, Metro, and railway transit.",
    is_published: true,
    is_featured: true,
  },
  {
    name: "PSK Aura",
    slug: "psk-aura-ghatkopar",
    location: "Hingwala Lane, Saibaba Nagar, Pant Nagar, Ghatkopar East, Mumbai",
    city: "Mumbai",
    builder: "PSK Group",
    price_display: "₹ 1.75 Cr Onwards",
    price_numeric: 17500000,
    status: "under-construction",
    cover_image: "https://pskaura.in/public/admin/images/PSK-Aura-elevation-image-1-04082025105835.jpg",
    bhk_options: "2, 3 & 4 BHK",
    min_bhk: 2,
    max_bhk: 4,
    possession: "March 2029",
    rera_number: "P51800080013",
    category: "Residential",
    tagline: "Boutique G+20 High-Rise Living in Prime Ghatkopar",
    gallery: JSON.stringify([
      "https://pskaura.in/public/admin/images/PSK-Aura-elevation-image-2-04082025105846.jpg",
      "https://pskaura.in/public/admin/images/PSK-Aura-banquet-hall-04082025105819.jpg",
      "https://pskaura.in/public/admin/images/PSK-Aura-mini-theatre-04082025105856.jpg",
      "https://pskaura.in/public/admin/images/PSK-Aura-multipurpose-court-04082025105908.jpg",
      "https://pskaura.in/public/admin/images/PSK-Aura-pergola-seating-04082025105921.jpg"
    ]),
    highlights: JSON.stringify([
      "G+20 Storey Standalone Boutique High-Rise Tower",
      "Open-to-Sky Landscaped Podium Garden",
      "3 Levels of Secure Basement Parking with EV Stations",
      "Exclusive Mini-Theatre, Reading Library & Toddler Zone",
      "450m from Proposed Pantnagar Metro & 600m from Ghatkopar Station",
      "Vastu-Compliant Architectural Floor Plans"
    ]),
    amenities: JSON.stringify(["Fitness Centre", "Open Podium Garden", "Mini Theatre", "Multipurpose Court", "Reading Library", "Kids Play Zone", "Basement Parking", "EV Charging"]),
    description: "PSK Aura is an exclusive G+20 storey boutique residential tower located on Hingwala Lane, Pant Nagar, Ghatkopar East. Offering ultra-luxurious 2, 3, and 4 BHK residences, PSK Aura seamlessly blends contemporary architectural aesthetics with serene lifestyle amenities including an open-to-sky podium garden, fitness centre, reading lounge, and 3 basement parking tiers, all within walking distance from Ghatkopar station and metro.",
    is_published: true,
    is_featured: true,
  },
  {
    name: "Silver Stellar",
    slug: "silver-stellar-ghatkopar",
    location: "Bhanushali Lane, Pant Nagar, Ghatkopar East, Mumbai",
    city: "Mumbai",
    builder: "Silver Group",
    price_display: "₹ 2.45 Cr Onwards",
    price_numeric: 24500000,
    status: "under-construction",
    cover_image: "https://silverstellar.in/assets/img/banners/Desktop-banner-1.jpg",
    bhk_options: "3 & 4 BHK",
    min_bhk: 3,
    max_bhk: 4,
    possession: "Dec 2028",
    rera_number: "P51800056223",
    category: "Residential",
    tagline: "Ultra-Spacious 3 & 4 BHK Residences by Silver Group",
    gallery: JSON.stringify([
      "https://silverstellar.in/assets/img/gallery/1.jpg",
      "https://silverstellar.in/assets/img/gallery/2.jpg",
      "https://silverstellar.in/assets/img/gallery/3.jpg",
      "https://silverstellar.in/assets/img/amenities/Grandlobby.jpg",
      "https://silverstellar.in/assets/img/amenities/Swimmingpool.jpg"
    ]),
    highlights: JSON.stringify([
      "Ultra-Spacious Luxury 3 & 4 BHK Residences",
      "Rooftop Sky Deck & Horizon Stargazing Lounge",
      "Grand Double-Height Italian Marble Entrance Lobby",
      "High-Speed Elevators with Power Backup",
      "Located in Prestigious Bhanushali Lane, Pant Nagar",
      "Smart Home Automation & Multi-Tier Biometric Security"
    ]),
    amenities: JSON.stringify(["Sky Lounge", "Infinity View Deck", "Gymnasium", "Italian Marble Lobby", "Yoga Pavilion", "Automated Parking", "24/7 Security"]),
    description: "Silver Stellar by Silver Group represents the pinnacle of spacious family living in Ghatkopar East. Situated in the serene neighborhood of Bhanushali Lane, Pant Nagar, this iconic standalone luxury tower offers palatial 3 & 4 BHK homes featuring floor-to-ceiling glass windows, imported marble finishes, a rooftop sky deck, and bespoke lifestyle amenities tailored for Mumbai's discerning elite.",
    is_published: true,
    is_featured: true,
  },
  {
    name: "Silver House",
    slug: "silver-house-ghatkopar",
    location: "Tilak Road, Opp. Gurukrupa Hotel, Ghatkopar East, Mumbai",
    city: "Mumbai",
    builder: "Silver Group",
    price_display: "₹ 1.15 Cr Onwards",
    price_numeric: 11500000,
    status: "under-construction",
    cover_image: "https://silverhouse.business/assets/img/banner/desk1.jpg",
    bhk_options: "Boutique Offices & High-Street Retail",
    min_bhk: 1,
    max_bhk: 1,
    possession: "Dec 2029",
    rera_number: "PC1180002500363",
    category: "Commercial",
    tagline: "G+16 Storey Iconic Commercial Landmark on Tilak Road",
    gallery: JSON.stringify([
      "https://silverhouse.business/assets/img/Silver-House.jpg",
      "https://silverhouse.business/assets/img/banner/desk1.jpg",
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80",
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80"
    ]),
    highlights: JSON.stringify([
      "Iconic G+16 Storey Glass Facade Commercial Landmark",
      "Double-Height Grand Drop-Off Reception Lobby",
      "Rooftop Business Lounge, Cafeteria & Open-Air Screening",
      "Pickle / Paddle Ball Court & Open-to-Sky Podium Deck",
      "2 Levels of Basement & Multi-Level Podium Parking",
      "Located on High-Footfall Tilak Road, Ghatkopar East"
    ]),
    amenities: JSON.stringify(["Business Lounge", "High-Speed Elevators", "Paddle Ball Court", "Cafeteria", "Amphitheatre", "Conference Rooms", "Basement Parking", "24/7 Security"]),
    description: "Silver House is a premier G+16 storey next-generation commercial tower developed by Silver Group on Tilak Road, Ghatkopar East. Built to world-class Grade-A corporate standards, it features flexible boutique office suites, high-visibility retail spaces, double-height grand entrance reception, rooftop open-air amphitheatre, paddle ball court, and advanced building management systems.",
    is_published: true,
    is_featured: true,
  },
  {
    name: "One Alag",
    slug: "alag-one-chembur",
    location: "Central Chembur / Ghatkopar Link, Chembur, Mumbai",
    city: "Mumbai",
    builder: "Alag Group",
    price_display: "₹ 95 Lac Onwards",
    price_numeric: 9500000,
    status: "under-construction",
    cover_image: "https://images.unsplash.com/photo-1554469384-e58fac16e23a?w=1200&q=80",
    bhk_options: "Smart Commercial Suites & Retail Outlets",
    min_bhk: 1,
    max_bhk: 1,
    possession: "Dec 2028",
    rera_number: "P51800052341",
    category: "Commercial",
    tagline: "Next-Gen Commercial & Retail Hub by Alag Group",
    gallery: JSON.stringify([
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1200&q=80",
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
      "https://images.unsplash.com/photo-1497215842964-222b430dc094?w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?w=1200&q=80"
    ]),
    highlights: JSON.stringify([
      "Grade-A Commercial Infrastructure by Reputed Alag Group",
      "High-Visibility Frontage on High Traffic Corridor",
      "Flexible Office Layouts with Self-Contained Restrooms",
      "Double-Height Designer Lobby with Biometric Access",
      "Minutes to Eastern Freeway, BKC Connector & LTT Station",
      "High Rental Yield & Capital Appreciation Potential"
    ]),
    amenities: JSON.stringify(["Grade-A Lobby", "High-Speed Elevators", "Business Center", "Power Backup", "BMS Surveillance", "Visitor Parking", "EV Charging"]),
    description: "One Alag by Alag Group is a high-profile commercial and retail hub situated along the prime Chembur-Ghatkopar growth corridor. Offering contemporary commercial suites and prime ground-level retail spaces, One Alag provides businesses with superior connectivity, modern architectural design, and state-of-the-art corporate infrastructure.",
    is_published: true,
    is_featured: true,
  },
  {
    name: "Shubham Artesia",
    slug: "shubham-artesia-ghatkopar",
    location: "328, Ramanarayan Narkar Marg, Pant Nagar, Ghatkopar East, Mumbai",
    city: "Mumbai",
    builder: "Shubham Group",
    price_display: "₹ 1.80 Cr Onwards",
    price_numeric: 18000000,
    status: "under-construction",
    cover_image: "https://shubhamartesiaghatkopareast.in/assets/img/common/metaimage.jpg",
    bhk_options: "2 & 3 BHK",
    min_bhk: 2,
    max_bhk: 3,
    possession: "Dec 2027",
    rera_number: "P51800079435",
    category: "Residential",
    tagline: "20-Storey Architectural Wonder in Heart of Pant Nagar",
    gallery: JSON.stringify([
      "https://shubhamartesiaghatkopareast.in/assets/img/common/metaimage.jpg",
      "https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=1200&q=80",
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=1200&q=80",
      "https://images.unsplash.com/photo-1616137466211-f939a420be84?w=1200&q=80"
    ]),
    highlights: JSON.stringify([
      "Magnificent 20-Storey Architectural High-Rise",
      "Air-Conditioned Gymnasium & Wellness Studio",
      "Grand Banquet Hall with Landscaped Party Lawn",
      "High-Street Retail Boulevard at Ground Level",
      "2 Minutes from Ghatkopar Railway Station & Metro",
      "Double-Height Grand Entrance Lobby with Concierge"
    ]),
    amenities: JSON.stringify(["AC Gymnasium", "Banquet Hall", "Party Lawn", "High-Street Retail", "Kids Play Area", "Smart Security", "Podium Parking"]),
    description: "Shubham Artesia by Shubham Group is a 20-storey architectural masterpiece located on Ramanarayan Narkar Marg in Pant Nagar, Ghatkopar East. Offering lavish 2 and 3 BHK luxury residences, the project features ground-level high-street retail, an air-conditioned fitness club, a grand banquet hall with party lawn, and unmatched transit connectivity to Eastern Express Highway and metro station.",
    is_published: true,
    is_featured: true,
  },

  // --- 2. EXTENDED PORTFOLIO ---
  {
    name: "MICL Aaradhya OnePark",
    slug: "micl-aaradhya-onepark",
    location: "60ft Road, Ghatkopar East, Mumbai",
    city: "Mumbai",
    builder: "MICL Group",
    price_display: "₹ 2.80 Cr Onwards",
    price_numeric: 28000000,
    status: "new-launch",
    cover_image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    bhk_options: "3, 4 & 5 BHK",
    min_bhk: 3,
    max_bhk: 5,
    possession: "Dec 2026",
    rera_number: "P51800000001",
    category: "Residential",
    tagline: "Ultra Luxury High-Rise on 60ft Road",
    gallery: JSON.stringify([
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=80"
    ]),
    highlights: JSON.stringify(["Rooftop Infinity Sky Pool", "Double-Height Grand Entrance Lobby", "Zen Garden & Yoga Pavilion", "Automated Smart Tower Parking"]),
    amenities: JSON.stringify(["Infinity Pool", "Gymnasium", "Concierge", "Sky Lounge", "24/7 Security"]),
    description: "Aaradhya OnePark brings ultra-luxury living to the prestigious 60ft Road in Ghatkopar East. A perfect blend of contemporary glass architecture, gold accents, and timeless elegance with panoramic city vistas.",
    is_published: true,
    is_featured: true,
  },
  {
    name: "Adani The Views",
    slug: "adani-the-views",
    location: "Pant Nagar, Ghatkopar East, Mumbai",
    city: "Mumbai",
    builder: "Adani Realty",
    price_display: "₹ 1.99 Cr Onwards",
    price_numeric: 19900000,
    status: "under-construction",
    cover_image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80",
    bhk_options: "2, 3 & 4 BHK",
    min_bhk: 2,
    max_bhk: 4,
    possession: "Dec 2027",
    rera_number: "P51900031165",
    category: "Residential",
    tagline: "Signature 200-ft Skywalk & Podium Living",
    gallery: JSON.stringify([
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=1200&q=80",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&q=80"
    ]),
    highlights: JSON.stringify(["200-foot Signature Skywalk", "Landscaped Podium Garden", "Adani Realty Build Quality Assurance", "10 Mins to Eastern Express Highway"]),
    amenities: JSON.stringify(["Skywalk", "Clubhouse", "Gymnasium", "Swimming Pool", "Kids Play Area"]),
    description: "Adani The Views in Pant Nagar, Ghatkopar East offers premium 2, 3 & 4 BHK residences featuring a signature 200-foot elevated skywalk, expansive podium gardens, and top-tier luxury amenities.",
    is_published: true,
    is_featured: true,
  },
  {
    name: "Orient Odyssey",
    slug: "orient-odyssey",
    location: "Ghatkopar East, Mumbai",
    city: "Mumbai",
    builder: "Orient Corp",
    price_display: "₹ 1.91 Cr Onwards",
    price_numeric: 19100000,
    status: "new-launch",
    cover_image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1200&q=80",
    bhk_options: "1, 2, 3 & 4 BHK",
    min_bhk: 1,
    max_bhk: 4,
    possession: "Dec 2030",
    rera_number: "PM1180002600214",
    category: "Residential",
    tagline: "Modern Twin-Tower Landmark in Ghatkopar",
    gallery: JSON.stringify([
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80",
      "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1200&q=80",
      "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=1200&q=80"
    ]),
    highlights: JSON.stringify(["2 Towers Spanning 0.36 Acres", "Yoga & Meditation Sky Deck", "Proximity to Ghatkopar Metro & Transit", "Smart Space Layouts"]),
    amenities: JSON.stringify(["Gymnasium", "Landscape Garden", "Jogging Track", "Yoga Deck", "24/7 Security"]),
    description: "Orient Odyssey by Orient Corp offers thoughtfully designed 1, 2, 3 & 4 BHK residences across two high-rise towers in Ghatkopar East, delivering modern comfort and curated lifestyle amenities.",
    is_published: true,
    is_featured: false,
  },
  {
    name: "9 Anemone Heights",
    slug: "9-anemone-heights",
    location: "90 Feet Rd, Pant Nagar, Ghatkopar East, Mumbai",
    city: "Mumbai",
    builder: "Anemone Homes LLP",
    price_display: "₹ 1.85 Cr Onwards",
    price_numeric: 18500000,
    status: "under-construction",
    cover_image: "https://images.unsplash.com/photo-1613490900233-141c5560d75d?w=1200&q=80",
    bhk_options: "2 & 3 BHK",
    min_bhk: 2,
    max_bhk: 3,
    possession: "June 2027",
    rera_number: "P51800099999",
    category: "Residential",
    tagline: "Rise Above The Skyline on 90 Feet Road",
    gallery: JSON.stringify([
      "https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=1200&q=80",
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=1200&q=80",
      "https://images.unsplash.com/photo-1616137466211-f939a420be84?w=1200&q=80",
      "https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?w=1200&q=80"
    ]),
    highlights: JSON.stringify(["Terrace Screening Zone & Cabanas", "7 High-speed Lifts per Tower", "2,000 Sq.Ft. Grand Entrance Lobby", "Wellness Hub & In-house Salon"]),
    amenities: JSON.stringify(["Multipurpose Studio", "Banquet Hall", "Wellness Hub", "Business Zone", "Terrace Screening"]),
    description: "Rising in the heart of Ghatkopar on 90 Feet Road, 9 Anemone Heights by Anemone Homes LLP offers premium city-view 2 & 3 BHK residences with curated amenities, grand lobbies, and high-speed elevator access.",
    is_published: true,
    is_featured: false,
  },
  {
    name: "House of Hiranandani Chembur",
    slug: "house-of-hiranandani-chembur",
    location: "Central Avenue, Chembur, Mumbai",
    city: "Mumbai",
    builder: "House of Hiranandani",
    price_display: "₹ 2.65 Cr Onwards",
    price_numeric: 26500000,
    status: "under-construction",
    cover_image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1200&q=80",
    bhk_options: "2, 3 & 4 BHK",
    min_bhk: 2,
    max_bhk: 4,
    possession: "Dec 2028",
    rera_number: "P51800032541",
    category: "Residential",
    tagline: "Signature Neo-Classical Elegance in Chembur",
    gallery: JSON.stringify([
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80",
      "https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=1200&q=80",
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200&q=80"
    ]),
    highlights: JSON.stringify(["Signature Neo-Classical Architecture", "Lush European Landscaped Gardens", "Grand Clubhouse & Swimming Pool", "5 Mins to BKC Connector & Eastern Freeway"]),
    amenities: JSON.stringify(["Swimming Pool", "Gymnasium", "Clubhouse", "Tennis Court", "Squash Court", "Banquet Hall", "Children's Play Area"]),
    description: "House of Hiranandani Chembur brings signature Neo-Classical architecture, expansive open greenery, and timeless luxury residences to Chembur. Featuring majestic archways, classical pillars, world-class amenities, and strategic connectivity to BKC and South Mumbai.",
    is_published: true,
    is_featured: false,
  },
  {
    name: "Rustomjee Balmoral Golf Links",
    slug: "rustomjee-balmoral-golf-links",
    location: "Golf Link Enclave, Chembur, Mumbai",
    city: "Mumbai",
    builder: "Rustomjee Group",
    price_display: "₹ 3.45 Cr Onwards",
    price_numeric: 34500000,
    status: "under-construction",
    cover_image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    bhk_options: "3, 4 & 5 BHK",
    min_bhk: 3,
    max_bhk: 5,
    possession: "June 2028",
    rera_number: "P51800048920",
    category: "Residential",
    tagline: "Palatial Golf-Facing Residences in Chembur",
    gallery: JSON.stringify([
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&q=80",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=1200&q=80"
    ]),
    highlights: JSON.stringify(["Unobstructed Golf Course Views", "Private Elevator Foyers for Every Residence", "Rooftop Infinity Pool & Sky Lounge", "Exclusive Cigar & Wine Pavilion"]),
    amenities: JSON.stringify(["Golf Simulator", "Infinity Pool", "Sky Lounge", "Private Theater", "Fitness Center", "Spa & Wellness Pavilion", "Concierge Service"]),
    description: "Rustomjee Balmoral Golf Links presents an unrepeatable luxury living experience overlooking panoramic golf course greens. Featuring private elevator foyers, expansive wrap-around sundecks, white-glove concierge, and a rooftop sky lounge.",
    is_published: true,
    is_featured: false,
  },
  {
    name: "Shubham Elegance",
    slug: "shubham-elegance-ghatkopar",
    location: "Ghatkopar East, Mumbai",
    city: "Mumbai",
    builder: "Shubham Group",
    price_display: "₹ 1.95 Cr",
    price_numeric: 19500000,
    status: "ready-to-move",
    cover_image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80",
    bhk_options: "2 & 3 BHK",
    min_bhk: 2,
    max_bhk: 3,
    possession: "Ready to Move",
    rera_number: "P51800000002",
    category: "Residential",
    tagline: "Premium Ready Homes",
    gallery: JSON.stringify([
      "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=1200&q=80",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200&q=80",
      "https://images.unsplash.com/photo-1598928506311-c55dd1b31043?w=1200&q=80"
    ]),
    highlights: JSON.stringify(["Grand Entrance Lobby", "Indoor Games Room", "Landscaped Podium", "Vaastu Compliant"]),
    amenities: JSON.stringify(["Security", "Play Area", "Garden"]),
    description: "Shubham Elegance offers premium ready-to-move-in residences in the heart of Ghatkopar East, providing excellent connectivity to key transit points and premium social infrastructure.",
    is_published: true,
    is_featured: false,
  },
  {
    name: "Happy Home Heights",
    slug: "happy-home-heights",
    location: "Garodia Nagar, Ghatkopar East",
    city: "Mumbai",
    builder: "Happy Home Group",
    price_display: "₹ 1.85 Cr",
    price_numeric: 18500000,
    status: "premium",
    cover_image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200&q=80",
    bhk_options: "2 & 3 BHK",
    min_bhk: 2,
    max_bhk: 3,
    possession: "Mid 2025",
    rera_number: "P51800000003",
    category: "Residential",
    tagline: "Smart Homes in Garodia Nagar",
    gallery: JSON.stringify([
      "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?w=1200&q=80",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=80",
      "https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=1200&q=80"
    ]),
    highlights: JSON.stringify(["Smart Home Automation", "Terrace Garden", "Children's Play Area", "Advanced Fire Safety"]),
    amenities: JSON.stringify(["Gym", "Kids Play Area", "Smart Security"]),
    description: "Experience modern living with smart home automation at Happy Home Heights. Situated in the peaceful enclave of Garodia Nagar, ensuring serenity amidst city life.",
    is_published: true,
    is_featured: false,
  },
  {
    name: "Ajmera Manhattan",
    slug: "ajmera-manhattan",
    location: "Ghatkopar East, Mumbai",
    city: "Mumbai",
    builder: "Ajmera Realty",
    price_display: "₹ 2.20 Cr Onwards",
    price_numeric: 22000000,
    status: "upcoming",
    cover_image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&q=80",
    bhk_options: "2, 3 & 4 BHK",
    min_bhk: 2,
    max_bhk: 4,
    possession: "Jan 2027",
    rera_number: "P51800000004",
    category: "Residential",
    tagline: "New York Lifestyle in Mumbai",
    gallery: JSON.stringify([
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80",
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80",
      "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=1200&q=80"
    ]),
    highlights: JSON.stringify(["Olympic Length Pool", "Grand Clubhouse", "Private Theatre", "Business Center"]),
    amenities: JSON.stringify(["Swimming Pool", "Theatre", "Gym", "Lounge"]),
    description: "Bringing the New York lifestyle to Ghatkopar. Ajmera Manhattan offers a premium living experience with expansive layouts and world-class leisure facilities.",
    is_published: true,
    is_featured: false,
  },
  {
    name: "Silver Harmony",
    slug: "silver-group-harmony",
    location: "Ghatkopar East, Mumbai",
    city: "Mumbai",
    builder: "Silver Group",
    price_display: "₹ 2.50 Cr",
    price_numeric: 25000000,
    status: "ready-to-move",
    cover_image: "https://images.unsplash.com/photo-1613490900233-141c5560d75d?w=1200&q=80",
    bhk_options: "3 & 4 BHK",
    min_bhk: 3,
    max_bhk: 4,
    possession: "Ready to Move",
    rera_number: "P51800000005",
    category: "Residential",
    tagline: "Architectural Brilliance",
    gallery: JSON.stringify([
      "https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=1200&q=80",
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=1200&q=80",
      "https://images.unsplash.com/photo-1616137466211-f939a420be84?w=1200&q=80"
    ]),
    highlights: JSON.stringify(["Double Height Lobby", "Italian Marble Flooring", "Senior Citizens Corner", "EV Charging Stations"]),
    amenities: JSON.stringify(["Lobby", "Garden", "Parking"]),
    description: "Silver Harmony stands as a testament to architectural brilliance. Enjoy spacious living with premium fittings, zero space wastage, and excellent cross-ventilation.",
    is_published: true,
    is_featured: false,
  },
  {
    name: "Yogeshwar Solitaire",
    slug: "yog-group-solitaire",
    location: "Near Station, Ghatkopar East",
    city: "Mumbai",
    builder: "Yog Group",
    price_display: "₹ 1.70 Cr",
    price_numeric: 17000000,
    status: "premium",
    cover_image: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=1200&q=80",
    bhk_options: "1, 2 & 3 BHK",
    min_bhk: 1,
    max_bhk: 3,
    possession: "March 2026",
    rera_number: "P51800000006",
    category: "Residential",
    tagline: "Unmatched Connectivity",
    gallery: JSON.stringify([
      "https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=1200&q=80",
      "https://images.unsplash.com/photo-1600607688969-a5bfcd64bd40?w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=1200&q=80"
    ]),
    highlights: JSON.stringify(["Terrace Garden & Walkway", "High-Speed Elevators", "Advanced CCTV Surveillance", "Multipurpose Hall"]),
    amenities: JSON.stringify(["Gym", "Hall", "Security"]),
    description: "Strategically located near Ghatkopar Station, Yogeshwar Solitaire offers unmatched connectivity without compromising on the luxury and tranquility of a premium residence.",
    is_published: true,
    is_featured: false,
  },
  {
    name: "Alag Horizon",
    slug: "alag-group-horizon",
    location: "MG Road, Ghatkopar East",
    city: "Mumbai",
    builder: "Alag Group",
    price_display: "₹ 2.15 Cr",
    price_numeric: 21500000,
    status: "upcoming",
    cover_image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80",
    bhk_options: "2 & 3 BHK",
    min_bhk: 2,
    max_bhk: 3,
    possession: "Oct 2025",
    rera_number: "P51800000007",
    category: "Residential",
    tagline: "Panoramic City Views",
    gallery: JSON.stringify([
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200&q=80"
    ]),
    highlights: JSON.stringify(["Rooftop Deck", "Barbeque Area", "Automated Parking", "Premium Bath Fittings"]),
    amenities: JSON.stringify(["Deck", "Parking", "Security"]),
    description: "Alag Horizon redefines the skyline of Ghatkopar East. With expansive decks offering panoramic city views and world-class fittings, it is designed for those who appreciate the finer things in life.",
    is_published: true,
    is_featured: false,
  },
  {
    name: "Drushti Sapphire",
    slug: "drushti-sapphire",
    location: "Ghatkopar East, Mumbai",
    city: "Mumbai",
    builder: "Drushti Group",
    price_display: "₹ 1.80 Cr",
    price_numeric: 18000000,
    status: "ready-to-move",
    cover_image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80",
    bhk_options: "2 & 3 BHK",
    min_bhk: 2,
    max_bhk: 3,
    possession: "Ready to Move",
    rera_number: "P51800000008",
    category: "Residential",
    tagline: "Vibrant Community Living",
    gallery: JSON.stringify([
      "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=1200&q=80",
      "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=1200&q=80",
      "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=1200&q=80"
    ]),
    highlights: JSON.stringify(["Community Hall", "Yoga & Meditation Zone", "Landscaped Gardens", "24/7 Power Backup"]),
    amenities: JSON.stringify(["Yoga", "Hall", "Garden"]),
    description: "Drushti Sapphire offers meticulously crafted homes with a focus on natural light and ventilation. It is a vibrant community located in the cultural heart of Ghatkopar.",
    is_published: true,
    is_featured: false,
  },
  {
    name: "Gurukrupa Marina",
    slug: "gurukrupa-marina",
    location: "Ghatkopar East, Mumbai",
    city: "Mumbai",
    builder: "Gurukrupa Group",
    price_display: "₹ 2.40 Cr",
    price_numeric: 24000000,
    status: "ultra-luxury",
    cover_image: "https://images.unsplash.com/photo-1616137466211-f939a420be84?w=1200&q=80",
    bhk_options: "3 & 4 BHK",
    min_bhk: 3,
    max_bhk: 4,
    possession: "Q4 2026",
    rera_number: "P51800000009",
    category: "Residential",
    tagline: "Majestic Clubhouse Living",
    gallery: JSON.stringify([
      "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?w=1200&q=80",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=80",
      "https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?w=1200&q=80"
    ]),
    highlights: JSON.stringify(["Grand Clubhouse", "Swimming Pool", "Jogging Track", "Co-working Space"]),
    amenities: JSON.stringify(["Pool", "Jogging Track", "Clubhouse"]),
    description: "Gurukrupa Marina offers vast open spaces, exceptional privacy, and a majestic clubhouse. A perfect sanctuary for your family in a bustling city.",
    is_published: true,
    is_featured: false,
  },
  {
    name: "Adityaraj Signature",
    slug: "adityaraj-signature",
    location: "Pant Nagar, Ghatkopar East",
    city: "Mumbai",
    builder: "Adityaraj Group",
    price_display: "₹ 1.45 Cr",
    price_numeric: 14500000,
    status: "premium",
    cover_image: "https://images.unsplash.com/photo-1599423300746-b62533397364?w=1200&q=80",
    bhk_options: "1 & 2 BHK",
    min_bhk: 1,
    max_bhk: 2,
    possession: "Dec 2025",
    rera_number: "P51800000010",
    category: "Residential",
    tagline: "Efficient Premium Layouts",
    gallery: JSON.stringify([
      "https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=1200&q=80"
    ]),
    highlights: JSON.stringify(["Fitness Center", "Indoor Games", "Rooftop Garden", "Reticulated Gas System"]),
    amenities: JSON.stringify(["Gym", "Garden", "Games"]),
    description: "Adityaraj Signature provides an excellent entry point into the premium Ghatkopar East market. Efficient layouts, superb build quality, and unmatched accessibility.",
    is_published: true,
    is_featured: false,
  }
];

async function seed() {
  let dbHost = process.env.DB_HOST || '127.0.0.1';
  if (dbHost === 'localhost') dbHost = '127.0.0.1';

  console.log(`Connecting to MySQL Database at ${dbHost}...`);
  
  try {
    const pool = mysql.createPool({
      host: dbHost,
      user: process.env.DB_USER || 'u278286324_user',
      password: process.env.DB_PASSWORD || 'Saverra@123',
      database: process.env.DB_NAME || 'u278286324_saverra',
      waitForConnections: true,
      connectionLimit: 10,
      queueLimit: 0,
      multipleStatements: true
    });

    console.log("Creating tables...");

    const tables = [
      `DROP TABLE IF EXISTS projects; CREATE TABLE projects (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        slug VARCHAR(255) NOT NULL UNIQUE,
        builder VARCHAR(255),
        category VARCHAR(100),
        city VARCHAR(100),
        location VARCHAR(255),
        price_display VARCHAR(100),
        price_numeric BIGINT,
        cover_image LONGTEXT,
        gallery JSON,
        bhk_options VARCHAR(255),
        min_bhk INT,
        max_bhk INT,
        possession VARCHAR(100),
        status VARCHAR(100),
        tagline VARCHAR(255),
        description TEXT,
        amenities JSON,
        highlights JSON,
        rera_number VARCHAR(100),
        latitude DECIMAL(10, 8),
        longitude DECIMAL(11, 8),
        is_featured BOOLEAN DEFAULT FALSE,
        is_published BOOLEAN DEFAULT TRUE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
      )`
    ];

    for (const sql of tables) {
      await pool.query(sql);
    }

    console.log("Tables created. Seeding " + allProjects.length + " projects...");

    for (const p of allProjects) {
      const keys = Object.keys(p);
      const values = keys.map(k => p[k]);
      const placeholders = keys.map(() => '?').join(', ');
      await pool.query(`INSERT INTO projects (${keys.join(', ')}) VALUES (${placeholders})`, values);
    }

    console.log("All " + allProjects.length + " projects seeded successfully into MySQL!");
    process.exit(0);
  } catch (error) {
    console.error("Database seed error:", error);
    process.exit(1);
  }
}

seed();
