/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AmenitiesRouteImport } from './routes/amenities'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FinancingRouteImport } from './routes/financing'
import { Route as NeighborhoodRouteImport } from './routes/neighborhood'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivateViewingRouteImport } from './routes/private-viewing'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SocialWallRouteImport } from './routes/social-wall'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAiStudioRouteImport } from './routes/admin.ai-studio'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminCareersRouteImport } from './routes/admin.careers'
import { Route as AdminFloorPlansRouteImport } from './routes/admin.floor-plans'
import { Route as AdminGuideRouteImport } from './routes/admin.guide'
import { Route as AdminInquiriesRouteImport } from './routes/admin.inquiries'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminMarketingRouteImport } from './routes/admin.marketing'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminRentalsRouteImport } from './routes/admin.rentals'
import { Route as AdminSocialRouteImport } from './routes/admin.social'
import { Route as AdminThemesRouteImport } from './routes/admin.themes'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AmenitiesRoute = AmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancingRoute = FinancingRouteImport.update({
  id: '/financing',
  path: '/financing',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighborhoodRoute = NeighborhoodRouteImport.update({
  id: '/neighborhood',
  path: '/neighborhood',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateViewingRoute = PrivateViewingRouteImport.update({
  id: '/private-viewing',
  path: '/private-viewing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialWallRoute = SocialWallRouteImport.update({
  id: '/social-wall',
  path: '/social-wall',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiStudioRoute = AdminAiStudioRouteImport.update({
  id: '/ai-studio',
  path: '/ai-studio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCareersRoute = AdminCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFloorPlansRoute = AdminFloorPlansRouteImport.update({
  id: '/floor-plans',
  path: '/floor-plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuideRoute = AdminGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRentalsRoute = AdminRentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSocialRoute = AdminSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AdminRoute,
} as any)
const AdminThemesRoute = AdminThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => AdminRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/amenities': typeof AmenitiesRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/financing': typeof FinancingRoute
  '/neighborhood': typeof NeighborhoodRoute
  '/privacy': typeof PrivacyRoute
  '/private-viewing': typeof PrivateViewingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/services': typeof ServicesRoute
  '/social-wall': typeof SocialWallRoute
  '/terms': typeof TermsRoute
  '/admin/ai-studio': typeof AdminAiStudioRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/floor-plans': typeof AdminFloorPlansRoute
  '/admin/guide': typeof AdminGuideRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/rentals': typeof AdminRentalsRoute
  '/admin/social': typeof AdminSocialRoute
  '/admin/themes': typeof AdminThemesRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/financing': typeof FinancingRoute
  '/neighborhood': typeof NeighborhoodRoute
  '/privacy': typeof PrivacyRoute
  '/private-viewing': typeof PrivateViewingRoute
  '/services': typeof ServicesRoute
  '/social-wall': typeof SocialWallRoute
  '/terms': typeof TermsRoute
  '/admin/ai-studio': typeof AdminAiStudioRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/floor-plans': typeof AdminFloorPlansRoute
  '/admin/guide': typeof AdminGuideRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/rentals': typeof AdminRentalsRoute
  '/admin/social': typeof AdminSocialRoute
  '/admin/themes': typeof AdminThemesRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/amenities': typeof AmenitiesRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/financing': typeof FinancingRoute
  '/neighborhood': typeof NeighborhoodRoute
  '/privacy': typeof PrivacyRoute
  '/private-viewing': typeof PrivateViewingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/services': typeof ServicesRoute
  '/social-wall': typeof SocialWallRoute
  '/terms': typeof TermsRoute
  '/admin/ai-studio': typeof AdminAiStudioRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/floor-plans': typeof AdminFloorPlansRoute
  '/admin/guide': typeof AdminGuideRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/rentals': typeof AdminRentalsRoute
  '/admin/social': typeof AdminSocialRoute
  '/admin/themes': typeof AdminThemesRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/amenities'
    | '/auth'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/faq'
    | '/financing'
    | '/neighborhood'
    | '/privacy'
    | '/private-viewing'
    | '/projects'
    | '/services'
    | '/social-wall'
    | '/terms'
    | '/admin/ai-studio'
    | '/admin/announcements'
    | '/admin/careers'
    | '/admin/floor-plans'
    | '/admin/guide'
    | '/admin/inquiries'
    | '/admin/integrations'
    | '/admin/marketing'
    | '/admin/projects'
    | '/admin/rentals'
    | '/admin/social'
    | '/admin/themes'
    | '/projects/$slug'
    | '/admin/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/amenities'
    | '/auth'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/faq'
    | '/financing'
    | '/neighborhood'
    | '/privacy'
    | '/private-viewing'
    | '/services'
    | '/social-wall'
    | '/terms'
    | '/admin/ai-studio'
    | '/admin/announcements'
    | '/admin/careers'
    | '/admin/floor-plans'
    | '/admin/guide'
    | '/admin/inquiries'
    | '/admin/integrations'
    | '/admin/marketing'
    | '/admin/projects'
    | '/admin/rentals'
    | '/admin/social'
    | '/admin/themes'
    | '/projects/$slug'
    | '/admin'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/amenities'
    | '/auth'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/faq'
    | '/financing'
    | '/neighborhood'
    | '/privacy'
    | '/private-viewing'
    | '/projects'
    | '/services'
    | '/social-wall'
    | '/terms'
    | '/admin/ai-studio'
    | '/admin/announcements'
    | '/admin/careers'
    | '/admin/floor-plans'
    | '/admin/guide'
    | '/admin/inquiries'
    | '/admin/integrations'
    | '/admin/marketing'
    | '/admin/projects'
    | '/admin/rentals'
    | '/admin/social'
    | '/admin/themes'
    | '/projects/$slug'
    | '/admin/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AmenitiesRoute: typeof AmenitiesRoute
  AuthRoute: typeof AuthRoute
  CareersRoute: typeof CareersRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FinancingRoute: typeof FinancingRoute
  NeighborhoodRoute: typeof NeighborhoodRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivateViewingRoute: typeof PrivateViewingRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  SocialWallRoute: typeof SocialWallRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amenities': {
      id: '/amenities'
      path: '/amenities'
      fullPath: '/amenities'
      preLoaderRoute: typeof AmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financing': {
      id: '/financing'
      path: '/financing'
      fullPath: '/financing'
      preLoaderRoute: typeof FinancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighborhood': {
      id: '/neighborhood'
      path: '/neighborhood'
      fullPath: '/neighborhood'
      preLoaderRoute: typeof NeighborhoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-viewing': {
      id: '/private-viewing'
      path: '/private-viewing'
      fullPath: '/private-viewing'
      preLoaderRoute: typeof PrivateViewingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-wall': {
      id: '/social-wall'
      path: '/social-wall'
      fullPath: '/social-wall'
      preLoaderRoute: typeof SocialWallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-studio': {
      id: '/admin/ai-studio'
      path: '/ai-studio'
      fullPath: '/admin/ai-studio'
      preLoaderRoute: typeof AdminAiStudioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/careers': {
      id: '/admin/careers'
      path: '/careers'
      fullPath: '/admin/careers'
      preLoaderRoute: typeof AdminCareersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/floor-plans': {
      id: '/admin/floor-plans'
      path: '/floor-plans'
      fullPath: '/admin/floor-plans'
      preLoaderRoute: typeof AdminFloorPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guide': {
      id: '/admin/guide'
      path: '/guide'
      fullPath: '/admin/guide'
      preLoaderRoute: typeof AdminGuideRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rentals': {
      id: '/admin/rentals'
      path: '/rentals'
      fullPath: '/admin/rentals'
      preLoaderRoute: typeof AdminRentalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/social': {
      id: '/admin/social'
      path: '/social'
      fullPath: '/admin/social'
      preLoaderRoute: typeof AdminSocialRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/themes': {
      id: '/admin/themes'
      path: '/themes'
      fullPath: '/admin/themes'
      preLoaderRoute: typeof AdminThemesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAiStudioRoute: typeof AdminAiStudioRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminCareersRoute: typeof AdminCareersRoute
  AdminFloorPlansRoute: typeof AdminFloorPlansRoute
  AdminGuideRoute: typeof AdminGuideRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminRentalsRoute: typeof AdminRentalsRoute
  AdminSocialRoute: typeof AdminSocialRoute
  AdminThemesRoute: typeof AdminThemesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiStudioRoute: AdminAiStudioRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminCareersRoute: AdminCareersRoute,
  AdminFloorPlansRoute: AdminFloorPlansRoute,
  AdminGuideRoute: AdminGuideRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminRentalsRoute: AdminRentalsRoute,
  AdminSocialRoute: AdminSocialRoute,
  AdminThemesRoute: AdminThemesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AmenitiesRoute: AmenitiesRoute,
  AuthRoute: AuthRoute,
  CareersRoute: CareersRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FinancingRoute: FinancingRoute,
  NeighborhoodRoute: NeighborhoodRoute,
  PrivacyRoute: PrivacyRoute,
  PrivateViewingRoute: PrivateViewingRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ServicesRoute: ServicesRoute,
  SocialWallRoute: SocialWallRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
